{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yontrack-mcp-chart.fullname" . }}
  labels:
    {{- include "yontrack-mcp-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  YONTRACK_TOKEN: {{ .Values.yontrack.token | quote }}
  {{- if .Values.oauth.authPassword }}
  YONTRACK_MCP_AUTH_PASSWORD: {{ .Values.oauth.authPassword | quote }}
  {{- end }}
{{- end }}
