apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yontrack-mcp-chart.fullname" . }}
  labels:
    {{- include "yontrack-mcp-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  YONTRACK_TOKEN: {{ .Values.yontrack.token | quote }}
  {{- if .Values.oidc.enabled }}
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
